default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS", 5) %>

development:
  <<: *default
  database: vantage_development

test:
  <<: *default
  database: vantage_test

production:
  # ---------- MAIN APP DB ----------
  primary:
    <<: *default
    url: <%= ENV.fetch("DATABASE_URL") %>

  # ---------- SOLID CACHE ----------
  cache:
    <<: *default
    url: <%= ENV.fetch("CACHE_DATABASE_URL", ENV.fetch("DATABASE_URL")) %>
    migrations_paths: db/cache_migrate

  # ---------- SOLID QUEUE ----------
  queue:
    <<: *default
    url: <%= ENV.fetch("QUEUE_DATABASE_URL", ENV.fetch("DATABASE_URL")) %>
    migrations_paths: db/queue_migrate

  # ---------- SOLID CABLE ----------
  cable:
    <<: *default
    url: <%= ENV.fetch("CABLE_DATABASE_URL", ENV.fetch("DATABASE_URL")) %>
    migrations_paths: db/cable_migrate
