default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: vantage_dokku_development
git add
test:
  <<: *default
  database: vantage_dokku_test

production:
  primary: &primary_production
    <<: *default
    url: <%= ENV["DATABASE_URL"] %>
  # ---------- SOLID CACHE ----------
  cache:
    <<: *primary_production
    url: <%= ENV["DATABASE_URL"] %>
    migrations_paths: db/cache_migrate
  # ---------- SOLID QUEUE ----------
  queue:
    <<: *primary_production
    url: <%= ENV["DATABASE_URL"] %>
    migrations_paths: db/queue_migrate
  # ---------- ACTION CABLE ----------
  cable:
    <<: *primary_production
    url: <%= ENV["DATABASE_URL"] %>
    migrations_paths: db/cable_migrate
