default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: vantage_dokku_development

test:
  <<: *default
  database: vantage_dokku_test

production:
  adapter: postgresql
  primary: &primary_production
    <<: *default
  url: <%= ENV['DATABASE_URL'] %>
  cache:
    <<: *primary_production
  queue:
    <<: *primary_production
  cable:
    <<: *primary_production
